name: AttackPlugin
version: 1.0-SNAPSHOT
author: SquidSquad
main: minecraft.squidsquad.MyPlugin
api-version: 1.16
#commands:
#   placearena:
#      description: places an arena
#      usage: /placearena width depth height
