name: AttackPlugin
version: 1.0-SNAPSHOT
author: SquidSquad
main: minecraft.squidsquad.MyPlugin
api-version: 1.16
commands:
   ping:
      description: returns pong
      usage: /ping
   setWind:
      description: sets a default value for the wind
      usage: /setWind
   spm:
      description: spawns a monster
      usage: /spm
#commands:
#   placearena:
#      description: places an arena
#      usage: /placearena width depth height
