name: AttackPlugin
version: 1.0-SNAPSHOT
author: SquidSquad
main: minecraft.squidsquad.MyPlugin
api-version: 1.16
commands:
   ping:
      description: returns pong
      usage: /ping
   setwinddir:
      description: sets the direction of the wind, reverts speed to 1
      usage: /setwinddir
   setwindspd:
      description: sets the strength of the wind
      usage: /setwindspd
   spm:
      description: spawns a monster
      usage: /spm
   getcatsword:
      description: Summons the great ExcaliPurr, that you may whisker away your enemies!
      usage: /getcatsword
#commands:
#   placearena:
#      description: places an arena
#      usage: /placearena width depth height
